{{- if .Values.route.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ .Release.Name }}-https"
  namespace: '{{ .Release.Namespace }}'
spec:
  parentRefs:
    - name: {{ .Values.route.parentRef.gatewayName }}
      namespace: {{ .Values.route.parentRef.namespace }}
  hostnames:
{{- range .Values.route.hostnames }}
    - {{ . }}
{{- end -}}
    {{.Values.route.backendRef | toYaml | nindent 2}}

{{- end }}
