{{- if .Values.route.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: "{{ .Release.Name }}-http"
  namespace: '{{ .Release.Namespace }}'
spec:
  parentRefs:
    - sectionName: http
      name: {{ .Values.route.parentRef.gatewayName }}
      namespace: {{ .Values.route.parentRef.namespace }}
  hostnames:
{{- range .Values.route.hostnames }}
    - {{ . }}
{{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}