apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproute-reader
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes","grpcroutes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httproute-reader-binding
subjects:
  - kind: ServiceAccount
    name: httproute-reader
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: httproute-reader
  apiGroup: rbac.authorization.k8s.io
