apiVersion: v1
data:
  index.html: |
    <h1 align="center">{{ .Values.heading }} </h1>
    <h2 align="center">{{ .Values.content }} </h2>
    
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: dvdemo
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: home
