apiVersion: v1
data:
  endpoints.yaml: |
        cna: https://vettom.github.io/api/cna.json
        pis: https://vettom.github.io/api/pis.json
  endpoints.json: |
        { "cna": "https://vettom.github.io/api/cna.json",
        "pis": "https://vettom.github.io/api/pis.json" }
kind: ConfigMap
metadata:
  name: endpoints
  namespace: default