route:
  enabled: true
  parentRef:
    gatewayName: vettom-gateway
    namespace: gateway
  hostnames:
    - bluegreen.dev.vettom.co.uk
  backendRef:
    rules:
    - backendRefs:
      - name: blue-bluegreen
        port: 8080
        weight: 80
      - name: green-bluegreen
        port: 8080
        weight: 20        
    - backendRefs:
      - name: red-bluegreen
        port: 8080
        weight: 1
      matches:
      - headers:
        - name: traffic
          type: Exact
          value: test
