{{- if and .Values.wiz.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiz-api-token
  namespace: wiz
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    purpose: Wiz application API key
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: eks-secretstore
    kind: ClusterSecretStore
  target:
    name: wiz-api-token
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: eks/wiz-sec
      property: clientId
  - secretKey: clientToken
    remoteRef:
      key: eks/wiz-sec
      property: clientToken 
{{- end -}}