{{- if and .Values.wiz.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sensor-image-pull
  namespace: wiz
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    purpose: Wiz docker registry key
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: eks-secretstore
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data: 
        .dockerconfigjson: '{"auths":{"{{ .dockerserver | lower }}":{"username":"{{ .dockerusername }}","password":"{{ .dockerpassword }}","auth":"{{ printf "%s:%s" .dockerusername .dockerpassword | b64enc }}"}}}'
  data:
    - secretKey: dockerserver
      remoteRef:
        key: eks/wiz-sec
        property: dockerserver
    - secretKey: dockerusername
      remoteRef:
        key: eks/wiz-sec
        property: dockerusername
    - secretKey: dockerpassword
      remoteRef:
        key: eks/wiz-sec
        property: dockerpassword
{{- end -}}