{{- if and .Values.wiz.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-integration
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wiz
    server: https://kubernetes.default.svc
  project: core
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.wiz.io/
    chart: wiz-kubernetes-integration
    targetRevision: {{ .Values.wiz.version }}
    helm:
      valuesObject:
        global:
          wizApiToken:
            secret:
              create: false
              name: wiz-api-token
        wiz-kubernetes-connector:
          enabled: true
          autoCreateConnector:
            clusterFlavor: EKS
        wiz-sensor:
          enabled: true
          imagePullSecret:
            create: false
            name: sensor-image-pull
{{- end -}}